global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']
    scrape_interval: 15s

  - job_name: 'login-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['login-service:8081']
    scrape_interval: 15s

  - job_name: 'employee-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['employee-service:8082']
    scrape_interval: 15s

  - job_name: 'access-control-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['access-control-service:8083']
    scrape_interval: 15s

  - job_name: 'alert-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['alert-service:8084']
    scrape_interval: 15s

  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth-service:8085']
    scrape_interval: 15s

  - job_name: 'saga-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['saga-service:8086']
    scrape_interval: 15s
